# Generated by Django 4.0.6 on 2023-06-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
