# Generated by Django 4.0.6 on 2023-06-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_album_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
