# Generated by Django 4.2.2 on 2023-06-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_artist_artist_bio_artist_artist_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="songs_list",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="yt_link",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
