# Generated by Django 4.2.2 on 2023-06-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_album_songs_list_album_yt_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="description",
            field=models.CharField(max_length=2500),
        ),
    ]
