# Generated by Django 4.2.2 on 2023-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_payment_order_remove_review_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
