# Generated by Django 4.2.2 on 2023-08-22 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_remove_cart_items_cartitem_cart_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('album', 'user')},
            },
        ),
    ]
