# Generated by Django 4.2.2 on 2023-08-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_albumrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_bio',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
